---

- name: install latest zsh
  homebrew: name=zsh state=latest

- name: add zsh to the allowed shells
  become: yes
  lineinfile: >
    dest=/etc/shells
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
    create=true
  with_items:
    - { regexp: '^/usr/local/bin/zsh', line: '/usr/local/bin/zsh' }

- name: register the current shell
  shell: echo $SHELL
  register: current_shell_result
  changed_when: False

- name: change shell for the current user
  become: yes
  shell: chsh -s /usr/local/bin/zsh {{ lookup('env','USER') }}
  when: current_shell_result.stdout != "/usr/local/bin/zsh"

- name: register the current root shell
  shell: dscl . -read /Users/root UserShell
  register: current_root_shell_result
  changed_when: False

- name: set the root user shell to zsh
  become: yes
  shell: dscl . -create /Users/root UserShell /usr/local/bin/zsh
  when: 'current_root_shell_result.stdout != "UserShell: /usr/local/bin/zsh"'

- name: tap the repos
  homebrew_tap: tap=superbrothers/zsh-kubectl-prompt state=present

- name: install personal cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - font-hack-nerd-font

- name: install personal brew apps
  homebrew: name={{item}} state=latest
  with_items:
    - zplug
    - zsh-autosuggestions
    - zsh-completions
    - zsh-git-prompt
    - zsh-history-substring-search
    - zsh-syntax-highlighting
    - zsh-kubectl-prompt
    
- name: place the different configuration files into place
  copy:
    src: '{{item}}'
    dest: '~/.{{ item }}'
  with_items:
    - zshrc
    - p10k.zsh
